[phases.setup]
nixPkgs = [
    "php82",
    "php82Extensions.intl",
    "php82Extensions.zip",
    "php82Extensions.pdo",
    "php82Extensions.pdo_mysql",
    "php82Extensions.bcmath",
    "php82Extensions.fileinfo",
    "php82Extensions.tokenizer",
    "php82Extensions.mbstring",
    "php82Extensions.openssl",
    "php82Extensions.curl",
    "php82Extensions.gd",
    "php82Packages.composer",
    "nodejs_20",
    "npm-9_x"
]

[phases.build]
cmds = [
    "npm install",
    "npm run build",
    "composer install --optimize-autoloader --no-dev --ignore-platform-reqs"
]

[start]
cmd = "php artisan migrate --force && php artisan storage:link && php artisan optimize && php artisan serve --host=0.0.0.0 --port=$PORT"
